# Generated by Django 5.2.8 on 2025-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_product_deal_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_step',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive'), ('converted', 'Converted')], default='prospect', max_length=20),
        ),
    ]
